"""Full 24-form paradigm audit — SLP1 golden tables.

Each golden dict covers (vibhakti 1..8 x vacana) with exact expected lists.
Twins (vibhAzA) are lists with 2 entries. Empty list = impossible number
(dvi-only / bahu-only stems).
"""
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pypanini.subanta import SubantaEngine

GOLDENS = {
    ("rAma", "puM"): {
        (1, "eka"): ["rAmaH"], (1, "dvi"): ["rAmO"], (1, "bahu"): ["rAmAH"],
        (2, "eka"): ["rAmam"], (2, "dvi"): ["rAmO"], (2, "bahu"): ["rAmAn"],
        (3, "eka"): ["rAmeRa"], (3, "dvi"): ["rAmAByAm"], (3, "bahu"): ["rAmEH"],
        (4, "eka"): ["rAmAya"], (4, "dvi"): ["rAmAByAm"], (4, "bahu"): ["rAmeByaH"],
        (5, "eka"): ["rAmAt"], (5, "dvi"): ["rAmAByAm"], (5, "bahu"): ["rAmeByaH"],
        (6, "eka"): ["rAmasya"], (6, "dvi"): ["rAmayoH"], (6, "bahu"): ["rAmARAm"],
        (7, "eka"): ["rAme"], (7, "dvi"): ["rAmayoH"], (7, "bahu"): ["rAmezu"],
        (8, "eka"): ["rAma"], (8, "dvi"): ["rAmO"], (8, "bahu"): ["rAmAH"],
    },
    ("sItA", "strI"): {
        (1, "eka"): ["sItA"], (1, "dvi"): ["sIte"], (1, "bahu"): ["sItAH"],
        (2, "eka"): ["sItAm"], (2, "dvi"): ["sIte"], (2, "bahu"): ["sItAH"],
        (3, "eka"): ["sItayA"], (3, "dvi"): ["sItAByAm"], (3, "bahu"): ["sItABiH"],
        (4, "eka"): ["sItAyE"], (4, "dvi"): ["sItAByAm"], (4, "bahu"): ["sItAByaH"],
        (5, "eka"): ["sItAyAH"], (5, "dvi"): ["sItAByAm"], (5, "bahu"): ["sItAByaH"],
        (6, "eka"): ["sItAyAH"], (6, "dvi"): ["sItayoH"], (6, "bahu"): ["sItAnAm"],
        (7, "eka"): ["sItAyAm"], (7, "dvi"): ["sItayoH"], (7, "bahu"): ["sItAsu"],
        (8, "eka"): ["sIte"], (8, "dvi"): ["sIte"], (8, "bahu"): ["sItAH"],
    },
    ("hari", "puM"): {
        (1, "eka"): ["hariH"], (1, "dvi"): ["haryO"], (1, "bahu"): ["harayaH"],
        (2, "eka"): ["harim"], (2, "dvi"): ["haryO"], (2, "bahu"): ["harIn"],
        (3, "eka"): ["haryA"], (3, "dvi"): ["hariByAm"], (3, "bahu"): ["hariBiH"],
        (4, "eka"): ["haraye"], (4, "dvi"): ["hariByAm"], (4, "bahu"): ["hariByaH"],
        (5, "eka"): ["hareH"], (5, "dvi"): ["hariByAm"], (5, "bahu"): ["hariByaH"],
        (6, "eka"): ["hareH"], (6, "dvi"): ["haryoH"], (6, "bahu"): ["harIRAm"],
        (7, "eka"): ["harO"], (7, "dvi"): ["haryoH"], (7, "bahu"): ["harizu"],
        (8, "eka"): ["hare"], (8, "dvi"): ["haryO"], (8, "bahu"): ["harayaH"],
    },
    ("nadI", "strI"): {
        (1, "eka"): ["nadIH"], (1, "dvi"): ["nadyO"], (1, "bahu"): ["nadyaH"],
        (2, "eka"): ["nadIm"], (2, "dvi"): ["nadyO"], (2, "bahu"): ["nadIH"],
        (3, "eka"): ["nadyA"], (3, "dvi"): ["nadIByAm"], (3, "bahu"): ["nadIBiH"],
        (4, "eka"): ["nadyE"], (4, "dvi"): ["nadIByAm"], (4, "bahu"): ["nadIByaH"],
        (5, "eka"): ["nadyAH"], (5, "dvi"): ["nadIByAm"], (5, "bahu"): ["nadIByaH"],
        (6, "eka"): ["nadyAH"], (6, "dvi"): ["nadyoH"], (6, "bahu"): ["nadInAm"],
        (7, "eka"): ["nadyAm"], (7, "dvi"): ["nadyoH"], (7, "bahu"): ["nadIzu"],
        (8, "eka"): ["nadi"], (8, "dvi"): ["nadyO"], (8, "bahu"): ["nadyaH"],
    },
    ("vAri", "napuMsaka"): {
        (1, "eka"): ["vAri"], (1, "dvi"): ["vAriRI"], (1, "bahu"): ["vArIRi"],
        (2, "eka"): ["vAri"], (2, "dvi"): ["vAriRI"], (2, "bahu"): ["vArIRi"],
        (3, "eka"): ["vAriRA"], (3, "dvi"): ["vAriByAm"], (3, "bahu"): ["vAriBiH"],
        (4, "eka"): ["vAriRe"], (4, "dvi"): ["vAriByAm"], (4, "bahu"): ["vAriByaH"],
        (5, "eka"): ["vAriRaH"], (5, "dvi"): ["vAriByAm"], (5, "bahu"): ["vAriByaH"],
        (6, "eka"): ["vAriRaH"], (6, "dvi"): ["vAriRoH"], (6, "bahu"): ["vArIRAm"],
        (7, "eka"): ["vAriRi"], (7, "dvi"): ["vAriRoH"], (7, "bahu"): ["vArizu"],
        (8, "eka"): ["vAri"], (8, "dvi"): ["vAriRI"], (8, "bahu"): ["vArIRi"],
    },
    ("kartf", "puM"): {
        (1, "eka"): ["kartA"], (1, "dvi"): ["kartArO"], (1, "bahu"): ["kartAraH"],
        (2, "eka"): ["kartAram"], (2, "dvi"): ["kartArO"], (2, "bahu"): ["kartFRaH"],
        (3, "eka"): ["kartrA"], (3, "dvi"): ["kartfByAm"], (3, "bahu"): ["kartfBiH"],
        (4, "eka"): ["kartre"], (4, "dvi"): ["kartfByAm"], (4, "bahu"): ["kartfByaH"],
        (5, "eka"): ["kartuH"], (5, "dvi"): ["kartfByAm"], (5, "bahu"): ["kartfByaH"],
        (6, "eka"): ["kartuH"], (6, "dvi"): ["kartroH"], (6, "bahu"): ["kartrARAm"],
        (7, "eka"): ["kartari"], (7, "dvi"): ["kartroH"], (7, "bahu"): ["kartfzu"],
        (8, "eka"): ["kartar"], (8, "dvi"): ["kartArO"], (8, "bahu"): ["kartAraH"],
    },
    ("rAjan", "puM"): {
        (1, "eka"): ["rAjA"], (1, "dvi"): ["rAjAnO"], (1, "bahu"): ["rAjAnaH"],
        (2, "eka"): ["rAjAnam"], (2, "dvi"): ["rAjAnO"], (2, "bahu"): ["rAjYaH"],
        (3, "eka"): ["rAjYA"], (3, "dvi"): ["rAjaByAm"], (3, "bahu"): ["rAjaBiH"],
        (4, "eka"): ["rAjYe"], (4, "dvi"): ["rAjaByAm"], (4, "bahu"): ["rAjaByaH"],
        (5, "eka"): ["rAjYaH"], (5, "dvi"): ["rAjaByAm"], (5, "bahu"): ["rAjaByaH"],
        (6, "eka"): ["rAjYaH"], (6, "dvi"): ["rAjYoH"], (6, "bahu"): ["rAjYAm"],
        (7, "eka"): ["rAjYi"], (7, "dvi"): ["rAjYoH"], (7, "bahu"): ["rAjasu"],
        (8, "eka"): ["rAjA"], (8, "dvi"): ["rAjAnO"], (8, "bahu"): ["rAjAnaH"],
    },
    ("manas", "napuMsaka"): {
        (1, "eka"): ["manaH"], (1, "dvi"): ["manasI"], (1, "bahu"): ["manAMsi"],
        (2, "eka"): ["manaH"], (2, "dvi"): ["manasI"], (2, "bahu"): ["manAMsi"],
        (3, "eka"): ["manasA"], (3, "dvi"): ["manoByAm"], (3, "bahu"): ["manoBiH"],
        (4, "eka"): ["manase"], (4, "dvi"): ["manoByAm"], (4, "bahu"): ["manoByaH"],
        (5, "eka"): ["manasaH"], (5, "dvi"): ["manoByAm"], (5, "bahu"): ["manoByaH"],
        (6, "eka"): ["manasaH"], (6, "dvi"): ["manasoH"], (6, "bahu"): ["manasAm"],
        (7, "eka"): ["manasi"], (7, "dvi"): ["manasoH"], (7, "bahu"): ["manaHsu"],
        (8, "eka"): ["manaH"], (8, "dvi"): ["manasI"], (8, "bahu"): ["manAMsi"],
    },
    ("vAc", "strI"): {
        (1, "eka"): ["vAk"], (1, "dvi"): ["vAcO"], (1, "bahu"): ["vAcaH"],
        (2, "eka"): ["vAcam"], (2, "dvi"): ["vAcO"], (2, "bahu"): ["vAcaH"],
        (3, "eka"): ["vAcA"], (3, "dvi"): ["vAgByAm"], (3, "bahu"): ["vAgBiH"],
        (4, "eka"): ["vAce"], (4, "dvi"): ["vAgByAm"], (4, "bahu"): ["vAgByaH"],
        (5, "eka"): ["vAcaH"], (5, "dvi"): ["vAgByAm"], (5, "bahu"): ["vAgByaH"],
        (6, "eka"): ["vAcaH"], (6, "dvi"): ["vAcoH"], (6, "bahu"): ["vAcAm"],
        (7, "eka"): ["vAci"], (7, "dvi"): ["vAcoH"], (7, "bahu"): ["vAkzu"],
        (8, "eka"): ["vAk"], (8, "dvi"): ["vAcO"], (8, "bahu"): ["vAcaH"],
    },
    ("go", "puM"): {
        (1, "eka"): ["gOH"], (1, "dvi"): ["gAvO"], (1, "bahu"): ["gAvaH"],
        (2, "eka"): ["gAm"], (2, "dvi"): ["gAvO"], (2, "bahu"): ["gAH"],
        (3, "eka"): ["gavA"], (3, "dvi"): ["goByAm"], (3, "bahu"): ["goBiH"],
        (4, "eka"): ["gave"], (4, "dvi"): ["goByAm"], (4, "bahu"): ["goByaH"],
        (5, "eka"): ["goH"], (5, "dvi"): ["goByAm"], (5, "bahu"): ["goByaH"],
        (6, "eka"): ["goH"], (6, "dvi"): ["gavoH"], (6, "bahu"): ["gavAm"],
        (7, "eka"): ["gavi"], (7, "dvi"): ["gavoH"], (7, "bahu"): ["gozu"],
        (8, "eka"): ["gOH"], (8, "dvi"): ["gAvO"], (8, "bahu"): ["gAvaH"],
    },
    ("tad", "puM"): {
        (1, "eka"): ["saH"], (1, "dvi"): ["tO"], (1, "bahu"): ["te"],
        (2, "eka"): ["tam"], (2, "dvi"): ["tO"], (2, "bahu"): ["tAn"],
        (3, "eka"): ["tena"], (3, "dvi"): ["tAByAm"], (3, "bahu"): ["tEH"],
        (4, "eka"): ["tasmE"], (4, "dvi"): ["tAByAm"], (4, "bahu"): ["teByaH"],
        (5, "eka"): ["tasmAt"], (5, "dvi"): ["tAByAm"], (5, "bahu"): ["teByaH"],
        (6, "eka"): ["tasya"], (6, "dvi"): ["tayoH"], (6, "bahu"): ["tezAm"],
        (7, "eka"): ["tasmin"], (7, "dvi"): ["tayoH"], (7, "bahu"): ["tezu"],
        (8, "eka"): ["saH"], (8, "dvi"): ["tO"], (8, "bahu"): ["te"],
    },
    ("tad", "napuMsaka"): {
        (1, "eka"): ["tat"], (1, "dvi"): ["te"], (1, "bahu"): ["tAni"],
        (2, "eka"): ["tat"], (2, "dvi"): ["te"], (2, "bahu"): ["tAni"],
        (3, "eka"): ["tena"], (3, "dvi"): ["tAByAm"], (3, "bahu"): ["tEH"],
        (4, "eka"): ["tasmE"], (4, "dvi"): ["tAByAm"], (4, "bahu"): ["teByaH"],
        (5, "eka"): ["tasmAt"], (5, "dvi"): ["tAByAm"], (5, "bahu"): ["teByaH"],
        (6, "eka"): ["tasya"], (6, "dvi"): ["tayoH"], (6, "bahu"): ["tezAm"],
        (7, "eka"): ["tasmin"], (7, "dvi"): ["tayoH"], (7, "bahu"): ["tezu"],
        (8, "eka"): ["tat"], (8, "dvi"): ["te"], (8, "bahu"): ["tAni"],
    },
}

GOLDENS2 = {
    ("saKi", "puM"): {
        (1, "eka"): ["saKA"], (1, "dvi"): ["saKAyO"], (1, "bahu"): ["saKAyaH"],
        (2, "eka"): ["saKAyam"], (2, "dvi"): ["saKAyO"], (2, "bahu"): ["saKyIn"],
        (3, "eka"): ["saKyA"], (3, "dvi"): ["saKiByAm"], (3, "bahu"): ["saKiBiH"],
        (4, "eka"): ["saKye"], (4, "dvi"): ["saKiByAm"], (4, "bahu"): ["saKiByaH"],
        (5, "eka"): ["saKyuH"], (5, "dvi"): ["saKiByAm"], (5, "bahu"): ["saKiByaH"],
        (6, "eka"): ["saKyuH"], (6, "dvi"): ["saKyoH"], (6, "bahu"): ["saKInAm"],
        (7, "eka"): ["saKyO"], (7, "dvi"): ["saKyoH"], (7, "bahu"): ["saKizu"],
        (8, "eka"): ["saKe"], (8, "dvi"): ["saKAyO"], (8, "bahu"): ["saKAyaH"],
    },
    ("asTi", "napuMsaka"): {
        (1, "eka"): ["asTi"], (1, "dvi"): ["asTinI"], (1, "bahu"): ["asTini"],
        (2, "eka"): ["asTi"], (2, "dvi"): ["asTinI"], (2, "bahu"): ["asTini"],
        (3, "eka"): ["asTnA"], (3, "dvi"): ["asTiByAm"], (3, "bahu"): ["asTiBiH"],
        (4, "eka"): ["asTne"], (4, "dvi"): ["asTiByAm"], (4, "bahu"): ["asTiByaH"],
        (5, "eka"): ["asTnaH"], (5, "dvi"): ["asTiByAm"], (5, "bahu"): ["asTiByaH"],
        (6, "eka"): ["asTnaH"], (6, "dvi"): ["asTnoH"], (6, "bahu"): ["asTnAm"],
        (7, "eka"): ["asTni"], (7, "dvi"): ["asTnoH"], (7, "bahu"): ["asTizu"],
        (8, "eka"): ["asTi"], (8, "dvi"): ["asTinI"], (8, "bahu"): ["asTini"],
    },
    ("sarva", "puM"): {
        (1, "eka"): ["sarvaH"], (1, "dvi"): ["sarvO"], (1, "bahu"): ["sarve"],
        (2, "eka"): ["sarvam"], (2, "dvi"): ["sarvO"], (2, "bahu"): ["sarvAn"],
        (3, "eka"): ["sarveRa"], (3, "dvi"): ["sarvAByAm"], (3, "bahu"): ["sarvEH"],
        (4, "eka"): ["sarvasmE"], (4, "dvi"): ["sarvAByAm"], (4, "bahu"): ["sarveByaH"],
        (5, "eka"): ["sarvasmAt"], (5, "dvi"): ["sarvAByAm"], (5, "bahu"): ["sarveByaH"],
        (6, "eka"): ["sarvasya"], (6, "dvi"): ["sarvayoH"], (6, "bahu"): ["sarvezAm"],
        (7, "eka"): ["sarvasmin"], (7, "dvi"): ["sarvayoH"], (7, "bahu"): ["sarvezu"],
        (8, "eka"): ["sarva"], (8, "dvi"): ["sarvO"], (8, "bahu"): ["sarve"],
    },
    ("adas", "puM"): {
        (1, "eka"): ["asO"], (1, "dvi"): ["amU"], (1, "bahu"): ["amI"],
        (2, "eka"): ["amum"], (2, "dvi"): ["amU"], (2, "bahu"): ["amUn"],
        (3, "eka"): ["amunA"], (3, "dvi"): ["amUByAm"], (3, "bahu"): ["amIBiH"],
        (4, "eka"): ["amuzmE"], (4, "dvi"): ["amUByAm"], (4, "bahu"): ["amIByaH"],
        (5, "eka"): ["amuzmAt"], (5, "dvi"): ["amUByAm"], (5, "bahu"): ["amIByaH"],
        (6, "eka"): ["amuzya"], (6, "dvi"): ["amuyoH"], (6, "bahu"): ["amIzAm"],
        (7, "eka"): ["amuzmin"], (7, "dvi"): ["amuyoH"], (7, "bahu"): ["amIzu"],
        (8, "eka"): ["asO"], (8, "dvi"): ["amU"], (8, "bahu"): ["amI"],
    },
    ("SrI", "strI"): {
        (1, "eka"): ["SrIH"], (1, "dvi"): ["SriyO"], (1, "bahu"): ["SriyaH"],
        (2, "eka"): ["Sriyam"], (2, "dvi"): ["SriyO"], (2, "bahu"): ["SriyaH"],
        (3, "eka"): ["SriyA"], (3, "dvi"): ["SrIByAm"], (3, "bahu"): ["SrIBiH"],
        (4, "eka"): ["SriyE"], (4, "dvi"): ["SrIByAm"], (4, "bahu"): ["SrIByaH"],
        (5, "eka"): ["SriyaH"], (5, "dvi"): ["SrIByAm"], (5, "bahu"): ["SrIByaH"],
        (6, "eka"): ["SriyaH"], (6, "dvi"): ["SriyoH"], (6, "bahu"): ["SriyAm"],
        (7, "eka"): ["Sriyam"], (7, "dvi"): ["SriyoH"], (7, "bahu"): ["SrIzu"],
        (8, "eka"): ["SrI"], (8, "dvi"): ["SriyO"], (8, "bahu"): ["SriyaH"],
    },
    ("pratyaYc", "puM"): {
        (1, "eka"): ["pratyaN"], (1, "dvi"): ["pratyaYcO"], (1, "bahu"): ["pratyaYcaH"],
        (2, "eka"): ["pratyaYcam"], (2, "dvi"): ["pratyaYcO"], (2, "bahu"): ["pratIcaH"],
        (3, "eka"): ["pratIcA"], (3, "dvi"): ["pratyagByAm"], (3, "bahu"): ["pratyagBiH"],
        (4, "eka"): ["pratIce"], (4, "dvi"): ["pratyagByAm"], (4, "bahu"): ["pratyagByaH"],
        (5, "eka"): ["pratIcaH"], (5, "dvi"): ["pratyagByAm"], (5, "bahu"): ["pratyagByaH"],
        (6, "eka"): ["pratIcaH"], (6, "dvi"): ["pratIcoH"], (6, "bahu"): ["pratIcAm"],
        (7, "eka"): ["pratIci"], (7, "dvi"): ["pratIcoH"], (7, "bahu"): ["pratyakzu"],
        (8, "eka"): ["pratyaN"], (8, "dvi"): ["pratyaYcO"], (8, "bahu"): ["pratyaYcaH"],
    },
    ("Sreyas", "puM"): {
        (1, "eka"): ["SreyAn"], (1, "dvi"): ["SreyAMsO"], (1, "bahu"): ["SreyAMsaH"],
        (2, "eka"): ["SreyAMsam"], (2, "dvi"): ["SreyAMsO"], (2, "bahu"): ["SreyasaH"],
        (3, "eka"): ["SreyasA"], (3, "dvi"): ["SreyoByAm"], (3, "bahu"): ["SreyoBiH"],
        (4, "eka"): ["Sreyase"], (4, "dvi"): ["SreyoByAm"], (4, "bahu"): ["SreyoByaH"],
        (5, "eka"): ["SreyasaH"], (5, "dvi"): ["SreyoByAm"], (5, "bahu"): ["SreyoByaH"],
        (6, "eka"): ["SreyasaH"], (6, "dvi"): ["SreyasoH"], (6, "bahu"): ["SreyasAm"],
        (7, "eka"): ["Sreyasi"], (7, "dvi"): ["SreyasoH"], (7, "bahu"): ["SreyaHsu"],
        (8, "eka"): ["Sreyan"], (8, "dvi"): ["SreyAMsO"], (8, "bahu"): ["SreyAMsaH"],
    },
    ("Bavat", "puM"): {
        (1, "eka"): ["BavAn"], (1, "dvi"): ["BavAntO"], (1, "bahu"): ["BavAntaH"],
        (2, "eka"): ["BavAntam"], (2, "dvi"): ["BavAntO"], (2, "bahu"): ["BavataH"],
        (3, "eka"): ["BavatA"], (3, "dvi"): ["BavadByAm"], (3, "bahu"): ["BavadBiH"],
        (4, "eka"): ["Bavate"], (4, "dvi"): ["BavadByAm"], (4, "bahu"): ["BavadByaH"],
        (5, "eka"): ["BavataH"], (5, "dvi"): ["BavadByAm"], (5, "bahu"): ["BavadByaH"],
        (6, "eka"): ["BavataH"], (6, "dvi"): ["BavatoH"], (6, "bahu"): ["BavatAm"],
        (7, "eka"): ["Bavati"], (7, "dvi"): ["BavatoH"], (7, "bahu"): ["Bavatsu"],
        (8, "eka"): ["BavAn"], (8, "dvi"): ["BavAntO"], (8, "bahu"): ["BavAntaH"],
    },
    ("gacCat", "puM"): {
        (1, "eka"): ["gacCan"], (1, "dvi"): ["gacCantO"], (1, "bahu"): ["gacCantaH"],
        (2, "eka"): ["gacCantam"], (2, "dvi"): ["gacCantO"], (2, "bahu"): ["gacCataH"],
        (3, "eka"): ["gacCatA"], (3, "dvi"): ["gacCadByAm"], (3, "bahu"): ["gacCadBiH"],
        (4, "eka"): ["gacCate"], (4, "dvi"): ["gacCadByAm"], (4, "bahu"): ["gacCadByaH"],
        (5, "eka"): ["gacCataH"], (5, "dvi"): ["gacCadByAm"], (5, "bahu"): ["gacCadByaH"],
        (6, "eka"): ["gacCataH"], (6, "dvi"): ["gacCatoH"], (6, "bahu"): ["gacCatAm"],
        (7, "eka"): ["gacCati"], (7, "dvi"): ["gacCatoH"], (7, "bahu"): ["gacCatsu"],
        (8, "eka"): ["gacCan"], (8, "dvi"): ["gacCantO"], (8, "bahu"): ["gacCantaH"],
    },
    ("cakfvas", "puM"): {
        (1, "eka"): ["cakfvAn"], (1, "dvi"): ["cakfvAMsO"], (1, "bahu"): ["cakfvAMsaH"],
        (2, "eka"): ["cakfvAMsam"], (2, "dvi"): ["cakfvAMsO"], (2, "bahu"): ["cakfuzaH"],
        (3, "eka"): ["cakfuzA"], (3, "dvi"): ["cakfvadByAm"], (3, "bahu"): ["cakfvadBiH"],
        (4, "eka"): ["cakfuze"], (4, "dvi"): ["cakfvadByAm"], (4, "bahu"): ["cakfvadByaH"],
        (5, "eka"): ["cakfuzaH"], (5, "dvi"): ["cakfvadByAm"], (5, "bahu"): ["cakfvadByaH"],
        (6, "eka"): ["cakfuzaH"], (6, "dvi"): ["cakfuzoH"], (6, "bahu"): ["cakfuzAm"],
        (7, "eka"): ["cakfuzi"], (7, "dvi"): ["cakfuzoH"], (7, "bahu"): ["cakfvatsu"],
        (8, "eka"): ["cakfvAn"], (8, "dvi"): ["cakfvAMsO"], (8, "bahu"): ["cakfvAMsaH"],
    },
    ("kftavat", "puM"): {
        (1, "eka"): ["kftavAn"], (1, "dvi"): ["kftavAntO"], (1, "bahu"): ["kftavAntaH"],
        (2, "eka"): ["kftavAntam"], (2, "dvi"): ["kftavAntO"], (2, "bahu"): ["kftavataH"],
        (3, "eka"): ["kftavatA"], (3, "dvi"): ["kftavadByAm"], (3, "bahu"): ["kftavadBiH"],
        (4, "eka"): ["kftavate"], (4, "dvi"): ["kftavadByAm"], (4, "bahu"): ["kftavadByaH"],
        (5, "eka"): ["kftavataH"], (5, "dvi"): ["kftavadByAm"], (5, "bahu"): ["kftavadByaH"],
        (6, "eka"): ["kftavataH"], (6, "dvi"): ["kftavatoH"], (6, "bahu"): ["kftavatAm"],
        (7, "eka"): ["kftavati"], (7, "dvi"): ["kftavatoH"], (7, "bahu"): ["kftavatsu"],
        (8, "eka"): ["kftavAn"], (8, "dvi"): ["kftavAntO"], (8, "bahu"): ["kftavAntaH"],
    },
}

GOLDENS3 = {
    ("rE", "puM"): {
        (1, "eka"): ["rAH"], (1, "dvi"): ["rAyO"], (1, "bahu"): ["rAyaH"],
        (2, "eka"): ["rAyam"], (2, "dvi"): ["rAyO"], (2, "bahu"): ["rAyaH"],
        (3, "eka"): ["rAyA"], (3, "dvi"): ["rAByAm"], (3, "bahu"): ["rABiH"],
        (4, "eka"): ["rAye"], (4, "dvi"): ["rAByAm"], (4, "bahu"): ["rAByaH"],
        (5, "eka"): ["rAyaH"], (5, "dvi"): ["rAByAm"], (5, "bahu"): ["rAByaH"],
        (6, "eka"): ["rAyaH"], (6, "dvi"): ["rAyoH"], (6, "bahu"): ["rAyAm"],
        (7, "eka"): ["rAyi"], (7, "dvi"): ["rAyoH"], (7, "bahu"): ["rAsu"],
        (8, "eka"): ["rAH"], (8, "dvi"): ["rAyO"], (8, "bahu"): ["rAyaH"],
    },
    ("nO", "strI"): {
        (1, "eka"): ["nOH"], (1, "dvi"): ["nAvO"], (1, "bahu"): ["nAvaH"],
        (2, "eka"): ["nAvam"], (2, "dvi"): ["nAvO"], (2, "bahu"): ["nAvaH"],
        (3, "eka"): ["nAvA"], (3, "dvi"): ["nOByAm"], (3, "bahu"): ["nOBiH"],
        (4, "eka"): ["nAve"], (4, "dvi"): ["nOByAm"], (4, "bahu"): ["nOByaH"],
        (5, "eka"): ["nAvaH"], (5, "dvi"): ["nOByAm"], (5, "bahu"): ["nOByaH"],
        (6, "eka"): ["nAvaH"], (6, "dvi"): ["nAvoH"], (6, "bahu"): ["nAvAm"],
        (7, "eka"): ["nAvi"], (7, "dvi"): ["nAvoH"], (7, "bahu"): ["nOzu"],
        (8, "eka"): ["nOH"], (8, "dvi"): ["nAvO"], (8, "bahu"): ["nAvaH"],
    },
    ("pati", "puM"): {
        (1, "eka"): ["patiH"], (1, "dvi"): ["patyO"], (1, "bahu"): ["patayaH"],
        (2, "eka"): ["patim"], (2, "dvi"): ["patyO"], (2, "bahu"): ["patIn"],
        (3, "eka"): ["patyA"], (3, "dvi"): ["patiByAm"], (3, "bahu"): ["patiBiH"],
        (4, "eka"): ["patye"], (4, "dvi"): ["patiByAm"], (4, "bahu"): ["patiByaH"],
        (5, "eka"): ["patyuH"], (5, "dvi"): ["patiByAm"], (5, "bahu"): ["patiByaH"],
        (6, "eka"): ["patyuH"], (6, "dvi"): ["patyoH"], (6, "bahu"): ["patInAm"],
        (7, "eka"): ["patyO"], (7, "dvi"): ["patyoH"], (7, "bahu"): ["patizu"],
        (8, "eka"): ["pate"], (8, "dvi"): ["patyO"], (8, "bahu"): ["patayaH"],
    },
    ("puMs", "puM"): {
        (1, "eka"): ["pumAn"], (1, "dvi"): ["pumAMsO"], (1, "bahu"): ["pumAMsaH"],
        (2, "eka"): ["pumAMsam"], (2, "dvi"): ["pumAMsO"], (2, "bahu"): ["puMsaH"],
        (3, "eka"): ["puMsA"], (3, "dvi"): ["pumByAm"], (3, "bahu"): ["pumBiH"],
        (4, "eka"): ["puMse"], (4, "dvi"): ["pumByAm"], (4, "bahu"): ["pumByaH"],
        (5, "eka"): ["puMsaH"], (5, "dvi"): ["pumByAm"], (5, "bahu"): ["pumByaH"],
        (6, "eka"): ["puMsaH"], (6, "dvi"): ["puMsoH"], (6, "bahu"): ["puMsAm"],
        (7, "eka"): ["puMsi"], (7, "dvi"): ["puMsoH"], (7, "bahu"): ["puMsu"],
        (8, "eka"): ["puman"], (8, "dvi"): ["pumAMsO"], (8, "bahu"): ["pumAMsaH"],
    },
    ("div", "strI"): {
        (1, "eka"): ["dyOH"], (1, "dvi"): ["divO"], (1, "bahu"): ["divaH"],
        (2, "eka"): ["divam"], (2, "dvi"): ["divO"], (2, "bahu"): ["divaH"],
        (3, "eka"): ["divA"], (3, "dvi"): ["dyuByAm"], (3, "bahu"): ["dyuBiH"],
        (4, "eka"): ["dive"], (4, "dvi"): ["dyuByAm"], (4, "bahu"): ["dyuByaH"],
        (5, "eka"): ["divaH"], (5, "dvi"): ["dyuByAm"], (5, "bahu"): ["dyuByaH"],
        (6, "eka"): ["divaH"], (6, "dvi"): ["divoH"], (6, "bahu"): ["divAm"],
        (7, "eka"): ["divi"], (7, "dvi"): ["divoH"], (7, "bahu"): ["dyuzu"],
        (8, "eka"): ["dyOH"], (8, "dvi"): ["divO"], (8, "bahu"): ["divaH"],
    },
    ("ahan", "napuMsaka"): {
        (1, "eka"): ["ahaH"], (1, "dvi"): ["ahanI"], (1, "bahu"): ["ahAni"],
        (2, "eka"): ["ahaH"], (2, "dvi"): ["ahanI"], (2, "bahu"): ["ahAni"],
        (3, "eka"): ["ahnA"], (3, "dvi"): ["ahoByAm"], (3, "bahu"): ["ahobhiH"],
        (4, "eka"): ["ahne"], (4, "dvi"): ["ahoByAm"], (4, "bahu"): ["ahoByaH"],
        (5, "eka"): ["ahnaH"], (5, "dvi"): ["ahoByAm"], (5, "bahu"): ["ahoByaH"],
        (6, "eka"): ["ahnaH"], (6, "dvi"): ["ahnoH"], (6, "bahu"): ["ahnAm"],
        (7, "eka"): ["ahni", "ahani"], (7, "dvi"): ["ahnoH"], (7, "bahu"): ["ahaHsu", "ahasu"],
        (8, "eka"): ["ahaH"], (8, "dvi"): ["ahanI"], (8, "bahu"): ["ahAni"],
    },
    ("paTin", "puM"): {
        (1, "eka"): ["panTAH"], (1, "dvi"): ["panTAnO"], (1, "bahu"): ["panTAnaH"],
        (2, "eka"): ["panTAnam"], (2, "dvi"): ["panTAnO"], (2, "bahu"): ["paTaH"],
        (3, "eka"): ["paTA"], (3, "dvi"): ["paTinByAm"], (3, "bahu"): ["paTinBiH"],
        (4, "eka"): ["paTe"], (4, "dvi"): ["paTinByAm"], (4, "bahu"): ["paTinByaH"],
        (5, "eka"): ["paTaH"], (5, "dvi"): ["paTinByAm"], (5, "bahu"): ["paTinByaH"],
        (6, "eka"): ["paTaH"], (6, "dvi"): ["paToH"], (6, "bahu"): ["paTAm"],
        (7, "eka"): ["paTi"], (7, "dvi"): ["paToH"], (7, "bahu"): ["paTinzu"],
        (8, "eka"): ["panTAH"], (8, "dvi"): ["panTAnO"], (8, "bahu"): ["panTAnaH"],
    },
    ("Svan", "puM"): {
        (1, "eka"): ["SvA"], (1, "dvi"): ["SvAnO"], (1, "bahu"): ["SvAnaH"],
        (2, "eka"): ["SvAnam"], (2, "dvi"): ["SvAnO"], (2, "bahu"): ["SunAH"],
        (3, "eka"): ["SunA"], (3, "dvi"): ["SvanByAm"], (3, "bahu"): ["SvanBiH"],
        (4, "eka"): ["Sune"], (4, "dvi"): ["SvanByAm"], (4, "bahu"): ["SvanByaH"],
        (5, "eka"): ["SunaH"], (5, "dvi"): ["SvanByAm"], (5, "bahu"): ["SvanByaH"],
        (6, "eka"): ["SunaH"], (6, "dvi"): ["SunoH"], (6, "bahu"): ["SunAm"],
        (7, "eka"): ["Suni"], (7, "dvi"): ["SunoH"], (7, "bahu"): ["Svanzu"],
        (8, "eka"): ["SvA"], (8, "dvi"): ["SvAnO"], (8, "bahu"): ["SvAnaH"],
    },
    ("mahat", "puM"): {
        (1, "eka"): ["mahAn"], (1, "dvi"): ["mahAntO"], (1, "bahu"): ["mahAntaH"],
        (2, "eka"): ["mahAntam"], (2, "dvi"): ["mahAntO"], (2, "bahu"): ["mahataH"],
        (3, "eka"): ["mahatA"], (3, "dvi"): ["mahadByAm"], (3, "bahu"): ["mahadBiH"],
        (4, "eka"): ["mahate"], (4, "dvi"): ["mahadByAm"], (4, "bahu"): ["mahadByaH"],
        (5, "eka"): ["mahataH"], (5, "dvi"): ["mahadByAm"], (5, "bahu"): ["mahadByaH"],
        (6, "eka"): ["mahataH"], (6, "dvi"): ["mahatoH"], (6, "bahu"): ["mahatAm"],
        (7, "eka"): ["mahati"], (7, "dvi"): ["mahatoH"], (7, "bahu"): ["mahatsu"],
        (8, "eka"): ["mahAn"], (8, "dvi"): ["mahAntO"], (8, "bahu"): ["mahAntaH"],
    },
    ("jagat", "napuMsaka"): {
        (1, "eka"): ["jagat"], (1, "dvi"): ["jagatI"], (1, "bahu"): ["jaganti"],
        (2, "eka"): ["jagat"], (2, "dvi"): ["jagatI"], (2, "bahu"): ["jaganti"],
        (3, "eka"): ["jagatA"], (3, "dvi"): ["jagadByAm"], (3, "bahu"): ["jagadBiH"],
        (4, "eka"): ["jagate"], (4, "dvi"): ["jagadByAm"], (4, "bahu"): ["jagadByaH"],
        (5, "eka"): ["jagataH"], (5, "dvi"): ["jagadByAm"], (5, "bahu"): ["jagadByaH"],
        (6, "eka"): ["jagataH"], (6, "dvi"): ["jagatoH"], (6, "bahu"): ["jagatAm"],
        (7, "eka"): ["jagati"], (7, "dvi"): ["jagatoH"], (7, "bahu"): ["jagatsu"],
        (8, "eka"): ["jagat"], (8, "dvi"): ["jagatI"], (8, "bahu"): ["jaganti"],
    },
    ("duh", "puM"): {
        (1, "eka"): ["duk"], (1, "dvi"): ["duhO"], (1, "bahu"): ["duhaH"],
        (2, "eka"): ["duham"], (2, "dvi"): ["duhO"], (2, "bahu"): ["duhaH"],
        (3, "eka"): ["duhA"], (3, "dvi"): ["dugByAm"], (3, "bahu"): ["dugBiH"],
        (4, "eka"): ["duhe"], (4, "dvi"): ["dugByAm"], (4, "bahu"): ["dugByaH"],
        (5, "eka"): ["duhaH"], (5, "dvi"): ["dugByAm"], (5, "bahu"): ["dugByaH"],
        (6, "eka"): ["duhaH"], (6, "dvi"): ["duhoH"], (6, "bahu"): ["duhAm"],
        (7, "eka"): ["duhi"], (7, "dvi"): ["duhoH"], (7, "bahu"): ["dukzu"],
        (8, "eka"): ["duk"], (8, "dvi"): ["duhO"], (8, "bahu"): ["duhaH"],
    },
    ("lih", "puM"): {
        (1, "eka"): ["liw"], (1, "dvi"): ["lihO"], (1, "bahu"): ["lihaH"],
        (2, "eka"): ["liham"], (2, "dvi"): ["lihO"], (2, "bahu"): ["lihaH"],
        (3, "eka"): ["lihA"], (3, "dvi"): ["liqByAm"], (3, "bahu"): ["liqBiH"],
        (4, "eka"): ["lihe"], (4, "dvi"): ["liqByAm"], (4, "bahu"): ["liqByaH"],
        (5, "eka"): ["lihaH"], (5, "dvi"): ["liqByAm"], (5, "bahu"): ["liqByaH"],
        (6, "eka"): ["lihaH"], (6, "dvi"): ["lihoH"], (6, "bahu"): ["lihAm"],
        (7, "eka"): ["lihi"], (7, "dvi"): ["lihoH"], (7, "bahu"): ["liwsu"],
        (8, "eka"): ["liw"], (8, "dvi"): ["lihO"], (8, "bahu"): ["lihaH"],
    },
    ("parivrAj", "puM"): {
        (1, "eka"): ["parivrAw"], (1, "dvi"): ["parivrAjO"], (1, "bahu"): ["parivrAjaH"],
        (2, "eka"): ["parivrAjam"], (2, "dvi"): ["parivrAjO"], (2, "bahu"): ["parivrAjaH"],
        (3, "eka"): ["parivrAjA"], (3, "dvi"): ["parivrAqByAm"], (3, "bahu"): ["parivrAqBiH"],
        (4, "eka"): ["parivrAje"], (4, "dvi"): ["parivrAqByAm"], (4, "bahu"): ["parivrAqByaH"],
        (5, "eka"): ["parivrAjaH"], (5, "dvi"): ["parivrAqByAm"], (5, "bahu"): ["parivrAqByaH"],
        (6, "eka"): ["parivrAjaH"], (6, "dvi"): ["parivrAjoH"], (6, "bahu"): ["parivrAjAm"],
        (7, "eka"): ["parivrAji"], (7, "dvi"): ["parivrAjoH"], (7, "bahu"): ["parivrAwzu"],
        (8, "eka"): ["parivrAw"], (8, "dvi"): ["parivrAjO"], (8, "bahu"): ["parivrAjaH"],
    },
    ("tri", "puM"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["trayaH"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["trIn"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["triBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["triByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["triByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["trayARAm"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["trizu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["trayaH"],
    },
    ("catur", "puM"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["catvAraH"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["caturaH"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["caturBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["caturByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["caturByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["caturRAm"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["caturzu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["catvAraH"],
    },
    ("paYcan", "puM"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["paYca"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["paYca"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["paYcaBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["paYcaByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["paYcaByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["paYcanAm"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["paYcasu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["paYca"],
    },
}

GOLDENS4 = {
    ("pitf", "puM"): {
        (1, "eka"): ["pitA"], (1, "dvi"): ["pitarO"], (1, "bahu"): ["pitaraH"],
        (2, "eka"): ["pitaram"], (2, "dvi"): ["pitarO"], (2, "bahu"): ["pitFRaH"],
        (3, "eka"): ["pitrA"], (3, "dvi"): ["pitfByAm"], (3, "bahu"): ["pitfBiH"],
        (4, "eka"): ["pitre"], (4, "dvi"): ["pitfByAm"], (4, "bahu"): ["pitfByaH"],
        (5, "eka"): ["pituH"], (5, "dvi"): ["pitfByAm"], (5, "bahu"): ["pitfByaH"],
        (6, "eka"): ["pituH"], (6, "dvi"): ["pitroH"], (6, "bahu"): ["pitFRAm"],
        (7, "eka"): ["pitari"], (7, "dvi"): ["pitroH"], (7, "bahu"): ["pitfzu"],
        (8, "eka"): ["pitar"], (8, "dvi"): ["pitarO"], (8, "bahu"): ["pitaraH"],
    },
    ("madhu", "napuMsaka"): {
        (1, "eka"): ["madhu"], (1, "dvi"): ["madhunI"], (1, "bahu"): ["madhURi"],
        (2, "eka"): ["madhu"], (2, "dvi"): ["madhunI"], (2, "bahu"): ["madhURi"],
        (3, "eka"): ["madhunA"], (3, "dvi"): ["madhuByAm"], (3, "bahu"): ["madhuBiH"],
        (4, "eka"): ["madhune"], (4, "dvi"): ["madhuByAm"], (4, "bahu"): ["madhuByaH"],
        (5, "eka"): ["madhunaH"], (5, "dvi"): ["madhuByAm"], (5, "bahu"): ["madhuByaH"],
        (6, "eka"): ["madhunaH"], (6, "dvi"): ["madhunoH"], (6, "bahu"): ["madhURAm"],
        (7, "eka"): ["madhuni"], (7, "dvi"): ["madhunoH"], (7, "bahu"): ["madhuzu"],
        (8, "eka"): ["madhu"], (8, "dvi"): ["madhunI"], (8, "bahu"): ["madhURi"],
    },
    ("havis", "napuMsaka"): {
        (1, "eka"): ["haviH"], (1, "dvi"): ["havisI"], (1, "bahu"): ["havIMsi"],
        (2, "eka"): ["haviH"], (2, "dvi"): ["havisI"], (2, "bahu"): ["havIMsi"],
        (3, "eka"): ["havizA"], (3, "dvi"): ["havoByAm"], (3, "bahu"): ["havoBiH"],
        (4, "eka"): ["havize"], (4, "dvi"): ["havoByAm"], (4, "bahu"): ["havoByaH"],
        (5, "eka"): ["havizaH"], (5, "dvi"): ["havoByAm"], (5, "bahu"): ["havoByaH"],
        (6, "eka"): ["havizaH"], (6, "dvi"): ["havizoH"], (6, "bahu"): ["havizAm"],
        (7, "eka"): ["havizi"], (7, "dvi"): ["havizoH"], (7, "bahu"): ["haviHsu"],
        (8, "eka"): ["haviH"], (8, "dvi"): ["havisI"], (8, "bahu"): ["havIMsi"],
    },
    ("sarvA", "strI"): {
        (1, "eka"): ["sarvA"], (1, "dvi"): ["sarve"], (1, "bahu"): ["sarvAH"],
        (2, "eka"): ["sarvAm"], (2, "dvi"): ["sarve"], (2, "bahu"): ["sarvAH"],
        (3, "eka"): ["sarvayA"], (3, "dvi"): ["sarvAByAm"], (3, "bahu"): ["sarvABiH"],
        (4, "eka"): ["sarvasyE"], (4, "dvi"): ["sarvAByAm"], (4, "bahu"): ["sarvAByaH"],
        (5, "eka"): ["sarvasyAH"], (5, "dvi"): ["sarvAByAm"], (5, "bahu"): ["sarvAByaH"],
        (6, "eka"): ["sarvasyAH"], (6, "dvi"): ["sarvayoH"], (6, "bahu"): ["sarvAsAm"],
        (7, "eka"): ["sarvasyAm"], (7, "dvi"): ["sarvayoH"], (7, "bahu"): ["sarvAsu"],
        (8, "eka"): ["sarve"], (8, "dvi"): ["sarve"], (8, "bahu"): ["sarvAH"],
    },
    ("zaz", "puM"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["zaw"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["zaw"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["zaqBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["zaqByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["zaqByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["zaRRam"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["zawsu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["zaw"],
    },
    ("azwan", "puM"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["azwO", "azwa"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["azwO", "azwa"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["azwaBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["azwaByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["azwaByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["azwanAm"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["azwasu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["azwO", "azwa"],
    },
    ("upAnah", "puM"): {
        (1, "eka"): ["upAnat"], (1, "dvi"): ["upAnahO"], (1, "bahu"): ["upAnahaH"],
        (2, "eka"): ["upAnaham"], (2, "dvi"): ["upAnahO"], (2, "bahu"): ["upAnahaH"],
        (3, "eka"): ["upAnahA"], (3, "dvi"): ["upAnadByAm"], (3, "bahu"): ["upAnadBiH"],
        (4, "eka"): ["upAnahe"], (4, "dvi"): ["upAnadByAm"], (4, "bahu"): ["upAnadByaH"],
        (5, "eka"): ["upAnahaH"], (5, "dvi"): ["upAnadByAm"], (5, "bahu"): ["upAnadByaH"],
        (6, "eka"): ["upAnahaH"], (6, "dvi"): ["upAnahoH"], (6, "bahu"): ["upAnahAm"],
        (7, "eka"): ["upAnahi"], (7, "dvi"): ["upAnahoH"], (7, "bahu"): ["upAnatsu"],
        (8, "eka"): ["upAnat"], (8, "dvi"): ["upAnahO"], (8, "bahu"): ["upAnahaH"],
    },
    ("jarA", "strI"): {
        (1, "eka"): ["jarA"], (1, "dvi"): ["jare", "jarasO"], (1, "bahu"): ["jarAH", "jarasaH"],
        (2, "eka"): ["jarAm"], (2, "dvi"): ["jare", "jarasO"], (2, "bahu"): ["jarAH", "jarasaH"],
        (3, "eka"): ["jarayA", "jarasA"], (3, "dvi"): ["jarAByAm"], (3, "bahu"): ["jarABiH"],
        (4, "eka"): ["jarAyE", "jarase"], (4, "dvi"): ["jarAByAm"], (4, "bahu"): ["jarAByaH"],
        (5, "eka"): ["jarAyAH", "jarasaH"], (5, "dvi"): ["jarAByAm"], (5, "bahu"): ["jarAByaH"],
        (6, "eka"): ["jarAyAH", "jarasaH"], (6, "dvi"): ["jarayoH"], (6, "bahu"): ["jarARAm"],
        (7, "eka"): ["jarAyAm", "jarasi"], (7, "dvi"): ["jarayoH"], (7, "bahu"): ["jarAsu"],
        (8, "eka"): ["jare", "jarasi"], (8, "dvi"): ["jare", "jarasO"], (8, "bahu"): ["jarAH", "jarasaH"],
    },
    ("krozwu", "puM"): {
        (1, "eka"): ["krozwA"], (1, "dvi"): ["krozwArO"], (1, "bahu"): ["krozwAraH"],
        (2, "eka"): ["krozwAram"], (2, "dvi"): ["krozwArO"], (2, "bahu"): ["krozwUn", "krozwFn"],
        (3, "eka"): ["krozwA", "krozwunA"], (3, "dvi"): ["krozwuByAm"], (3, "bahu"): ["krozwuBiH"],
        (4, "eka"): ["krozwe", "krozwave"], (4, "dvi"): ["krozwuByAm"], (4, "bahu"): ["krozwuByaH"],
        (5, "eka"): ["krozwuH"], (5, "dvi"): ["krozwuByAm"], (5, "bahu"): ["krozwuByaH"],
        (6, "eka"): ["krozwuH"], (6, "dvi"): ["krozwvoH", "krozwroH"], (6, "bahu"): ["krozwUnAm", "krozwFRam"],
        (7, "eka"): ["krozwO"], (7, "dvi"): ["krozwvoH", "krozwroH"], (7, "bahu"): ["krozwuzu"],
        (8, "eka"): ["krozwo"], (8, "dvi"): ["krozwArO"], (8, "bahu"): ["krozwAraH"],
    },
    ("ap", "strI"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["ApaH"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["apaH"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["adBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["adByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["adByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["apAm"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["apsu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["ApaH"],
    },
    ("anaQuh", "puM"): {
        (1, "eka"): ["anaQvAn"], (1, "dvi"): ["anaQvAMsO"], (1, "bahu"): ["anaQuhaH"],
        (2, "eka"): ["anaQvAMsam"], (2, "dvi"): ["anaQvAMsO"], (2, "bahu"): ["anaQuhaH"],
        (3, "eka"): ["anaQuhA"], (3, "dvi"): ["anaQudByAm"], (3, "bahu"): ["anaQudBiH"],
        (4, "eka"): ["anaQuhe"], (4, "dvi"): ["anaQudByAm"], (4, "bahu"): ["anaQudByaH"],
        (5, "eka"): ["anaQuhaH"], (5, "dvi"): ["anaQudByAm"], (5, "bahu"): ["anaQudByaH"],
        (6, "eka"): ["anaQuhaH"], (6, "dvi"): ["anaQuhoH"], (6, "bahu"): ["anaQuhAm"],
        (7, "eka"): ["anaQuhi"], (7, "dvi"): ["anaQuhoH"], (7, "bahu"): ["anaQutsu"],
        (8, "eka"): ["anaQvan"], (8, "dvi"): ["anaQvAMsO"], (8, "bahu"): ["anaQuhaH"],
    },
}

GOLDENS5 = {
    ("mati", "strI"): {
        (1, "eka"): ["matiH"], (1, "dvi"): ["matyO"], (1, "bahu"): ["matayaH"],
        (2, "eka"): ["matim"], (2, "dvi"): ["matyO"], (2, "bahu"): ["matIn"],
        (3, "eka"): ["matyA"], (3, "dvi"): ["matiByAm"], (3, "bahu"): ["matiBiH"],
        (4, "eka"): ["mataye", "matyE"], (4, "dvi"): ["matiByAm"], (4, "bahu"): ["matiByaH"],
        (5, "eka"): ["mateH", "matyAH"], (5, "dvi"): ["matiByAm"], (5, "bahu"): ["matiByaH"],
        (6, "eka"): ["mateH", "matyAH"], (6, "dvi"): ["matyoH"], (6, "bahu"): ["matInAm"],
        (7, "eka"): ["matO", "matyAm"], (7, "dvi"): ["matyoH"], (7, "bahu"): ["matizu"],
        (8, "eka"): ["mate"], (8, "dvi"): ["matyO"], (8, "bahu"): ["matayaH"],
    },
    ("svasf", "strI"): {
        (1, "eka"): ["svasA"], (1, "dvi"): ["svasArO"], (1, "bahu"): ["svasAraH"],
        (2, "eka"): ["svasAram"], (2, "dvi"): ["svasArO"], (2, "bahu"): ["svasFRaH"],
        (3, "eka"): ["svasrA"], (3, "dvi"): ["svasfByAm"], (3, "bahu"): ["svasfBiH"],
        (4, "eka"): ["svasre"], (4, "dvi"): ["svasfByAm"], (4, "bahu"): ["svasfByaH"],
        (5, "eka"): ["svasuH"], (5, "dvi"): ["svasfByAm"], (5, "bahu"): ["svasfByaH"],
        (6, "eka"): ["svasuH"], (6, "dvi"): ["svasroH"], (6, "bahu"): ["svasrARAm"],
        (7, "eka"): ["svasari"], (7, "dvi"): ["svasroH"], (7, "bahu"): ["svasfzu"],
        (8, "eka"): ["svasar"], (8, "dvi"): ["svasArO"], (8, "bahu"): ["svasAraH"],
    },
    ("kim", "puM"): {
        (1, "eka"): ["kaH"], (1, "dvi"): ["kO"], (1, "bahu"): ["ke"],
        (2, "eka"): ["kam"], (2, "dvi"): ["kO"], (2, "bahu"): ["kAn"],
        (3, "eka"): ["kena"], (3, "dvi"): ["kAByAm"], (3, "bahu"): ["kEH"],
        (4, "eka"): ["kasmE"], (4, "dvi"): ["kAByAm"], (4, "bahu"): ["keByaH"],
        (5, "eka"): ["kasmAt"], (5, "dvi"): ["kAByAm"], (5, "bahu"): ["keByaH"],
        (6, "eka"): ["kasya"], (6, "dvi"): ["kayoH"], (6, "bahu"): ["kezAm"],
        (7, "eka"): ["kasmin"], (7, "dvi"): ["kayoH"], (7, "bahu"): ["kezu"],
        (8, "eka"): ["kaH"], (8, "dvi"): ["kO"], (8, "bahu"): ["ke"],
    },
    ("idam", "puM"): {
        (1, "eka"): ["ayam"], (1, "dvi"): ["imO"], (1, "bahu"): ["ime"],
        (2, "eka"): ["imam"], (2, "dvi"): ["imO"], (2, "bahu"): ["imAn"],
        (3, "eka"): ["anena"], (3, "dvi"): ["AByAm"], (3, "bahu"): ["eBiH"],
        (4, "eka"): ["asmE"], (4, "dvi"): ["AByAm"], (4, "bahu"): ["eByaH"],
        (5, "eka"): ["asmAt"], (5, "dvi"): ["AByAm"], (5, "bahu"): ["eByaH"],
        (6, "eka"): ["asya"], (6, "dvi"): ["anayoH"], (6, "bahu"): ["ezAm"],
        (7, "eka"): ["asmin"], (7, "dvi"): ["anayoH"], (7, "bahu"): ["ezu"],
        (8, "eka"): ["ayam"], (8, "dvi"): ["imO"], (8, "bahu"): ["ime"],
    },
    ("karman", "napuMsaka"): {
        (1, "eka"): ["karma"], (1, "dvi"): ["karmanI"], (1, "bahu"): ["karmARi"],
        (2, "eka"): ["karma"], (2, "dvi"): ["karmanI"], (2, "bahu"): ["karmARi"],
        (3, "eka"): ["karmanA"], (3, "dvi"): ["karmaByAm"], (3, "bahu"): ["karmaBiH"],
        (4, "eka"): ["karmane"], (4, "dvi"): ["karmaByAm"], (4, "bahu"): ["karmaByaH"],
        (5, "eka"): ["karmanaH"], (5, "dvi"): ["karmaByAm"], (5, "bahu"): ["karmaByaH"],
        (6, "eka"): ["karmanaH"], (6, "dvi"): ["karmanoH"], (6, "bahu"): ["karmanAm"],
        (7, "eka"): ["karmani"], (7, "dvi"): ["karmanoH"], (7, "bahu"): ["karmasu"],
        (8, "eka"): ["karma"], (8, "dvi"): ["karmanI"], (8, "bahu"): ["karmARi"],
    },
    ("brahman", "napuMsaka"): {
        (1, "eka"): ["brahma"], (1, "dvi"): ["brahmanI"], (1, "bahu"): ["brahmARi"],
        (2, "eka"): ["brahma"], (2, "dvi"): ["brahmanI"], (2, "bahu"): ["brahmARi"],
        (3, "eka"): ["brahmanA"], (3, "dvi"): ["brahmaByAm"], (3, "bahu"): ["brahmaBiH"],
        (4, "eka"): ["brahmane"], (4, "dvi"): ["brahmaByAm"], (4, "bahu"): ["brahmaByaH"],
        (5, "eka"): ["brahmanaH"], (5, "dvi"): ["brahmaByAm"], (5, "bahu"): ["brahmaByaH"],
        (6, "eka"): ["brahmanaH"], (6, "dvi"): ["brahmanoH"], (6, "bahu"): ["brahmanAm"],
        (7, "eka"): ["brahmani"], (7, "dvi"): ["brahmanoH"], (7, "bahu"): ["brahmasu"],
        (8, "eka"): ["brahma"], (8, "dvi"): ["brahmanI"], (8, "bahu"): ["brahmARi"],
    },
    ("nAman", "napuMsaka"): {
        (1, "eka"): ["nAma"], (1, "dvi"): ["nAmanI"], (1, "bahu"): ["nAmAni"],
        (2, "eka"): ["nAma"], (2, "dvi"): ["nAmanI"], (2, "bahu"): ["nAmAni"],
        (3, "eka"): ["nAmnA", "nAmanA"], (3, "dvi"): ["nAmaByAm"], (3, "bahu"): ["nAmaBiH"],
        (4, "eka"): ["nAmne"], (4, "dvi"): ["nAmaByAm"], (4, "bahu"): ["nAmaByaH"],
        (5, "eka"): ["nAmnaH"], (5, "dvi"): ["nAmaByAm"], (5, "bahu"): ["nAmaByaH"],
        (6, "eka"): ["nAmnaH"], (6, "dvi"): ["nAmnoH"], (6, "bahu"): ["nAmnAm"],
        (7, "eka"): ["nAmni"], (7, "dvi"): ["nAmnoH"], (7, "bahu"): ["nAmasu"],
        (8, "eka"): ["nAma"], (8, "dvi"): ["nAmanI"], (8, "bahu"): ["nAmAni"],
    },
    ("Atman", "puM"): {
        (1, "eka"): ["AtmA"], (1, "dvi"): ["AtmAnO"], (1, "bahu"): ["AtmAnaH"],
        (2, "eka"): ["AtmAnam"], (2, "dvi"): ["AtmAnO"], (2, "bahu"): ["AtmanaH"],
        (3, "eka"): ["AtmanA"], (3, "dvi"): ["AtmaByAm"], (3, "bahu"): ["AtmaBiH"],
        (4, "eka"): ["Atmane"], (4, "dvi"): ["AtmaByAm"], (4, "bahu"): ["AtmaByaH"],
        (5, "eka"): ["AtmanaH"], (5, "dvi"): ["AtmaByAm"], (5, "bahu"): ["AtmaByaH"],
        (6, "eka"): ["AtmanaH"], (6, "dvi"): ["AtmanoH"], (6, "bahu"): ["AtmanAm"],
        (7, "eka"): ["Atmani"], (7, "dvi"): ["AtmanoH"], (7, "bahu"): ["Atmasu"],
        (8, "eka"): ["AtmA"], (8, "dvi"): ["AtmAnO"], (8, "bahu"): ["AtmAnaH"],
    },
    ("Danin", "puM"): {
        (1, "eka"): ["DanI"], (1, "dvi"): ["DaninO"], (1, "bahu"): ["DaninaH"],
        (2, "eka"): ["Daninam"], (2, "dvi"): ["DaninO"], (2, "bahu"): ["DaninaH"],
        (3, "eka"): ["DaninA"], (3, "dvi"): ["DaninByAm"], (3, "bahu"): ["DaninBiH"],
        (4, "eka"): ["Danine"], (4, "dvi"): ["DaninByAm"], (4, "bahu"): ["DaninByaH"],
        (5, "eka"): ["DaninaH"], (5, "dvi"): ["DaninByAm"], (5, "bahu"): ["DaninByaH"],
        (6, "eka"): ["DaninaH"], (6, "dvi"): ["DaninoH"], (6, "bahu"): ["DaninAm"],
        (7, "eka"): ["Danini"], (7, "dvi"): ["DaninoH"], (7, "bahu"): ["DanIzu"],
        (8, "eka"): ["DanI"], (8, "dvi"): ["DaninO"], (8, "bahu"): ["DaninaH"],
    },
    ("vaDU", "strI"): {
        (1, "eka"): ["vaDUH"], (1, "dvi"): ["vaDvO"], (1, "bahu"): ["vaDvaH"],
        (2, "eka"): ["vaDUm"], (2, "dvi"): ["vaDvO"], (2, "bahu"): ["vaDUH"],
        (3, "eka"): ["vaDvA"], (3, "dvi"): ["vaDUByAm"], (3, "bahu"): ["vaDUBiH"],
        (4, "eka"): ["vaDvE"], (4, "dvi"): ["vaDUByAm"], (4, "bahu"): ["vaDUByaH"],
        (5, "eka"): ["vaDvAH"], (5, "dvi"): ["vaDUByAm"], (5, "bahu"): ["vaDUByaH"],
        (6, "eka"): ["vaDvAH"], (6, "dvi"): ["vaDvoH"], (6, "bahu"): ["vaDUnAm"],
        (7, "eka"): ["vaDvAm"], (7, "dvi"): ["vaDvoH"], (7, "bahu"): ["vaDUzu"],
        (8, "eka"): ["vaDu"], (8, "dvi"): ["vaDvO"], (8, "bahu"): ["vaDvaH"],
    },
    ("tri", "strI"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["tisraH"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["tisfH"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["tisfBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["tisfByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["tisfByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["tisfRAm"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["tisfzu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["tisraH"],
    },
    ("catur", "strI"): {
        (1, "eka"): [], (1, "dvi"): [], (1, "bahu"): ["catasraH"],
        (2, "eka"): [], (2, "dvi"): [], (2, "bahu"): ["catasraH"],
        (3, "eka"): [], (3, "dvi"): [], (3, "bahu"): ["catasfBiH"],
        (4, "eka"): [], (4, "dvi"): [], (4, "bahu"): ["catasfByaH"],
        (5, "eka"): [], (5, "dvi"): [], (5, "bahu"): ["catasfByaH"],
        (6, "eka"): [], (6, "dvi"): [], (6, "bahu"): ["catasfRAm"],
        (7, "eka"): [], (7, "dvi"): [], (7, "bahu"): ["catasfzu"],
        (8, "eka"): [], (8, "dvi"): [], (8, "bahu"): ["catasraH"],
    },
}

GOLDENS6 = {
    ("kim", "strI"): {
        (1, "eka"): ["kA"], (1, "dvi"): ["ke"], (1, "bahu"): ["kAH"],
        (2, "eka"): ["kAm"], (2, "dvi"): ["ke"], (2, "bahu"): ["kAH"],
        (3, "eka"): ["kayA"], (3, "dvi"): ["kAByAm"], (3, "bahu"): ["kABiH"],
        (4, "eka"): ["kasyE"], (4, "dvi"): ["kAByAm"], (4, "bahu"): ["kAByaH"],
        (5, "eka"): ["kasyAH"], (5, "dvi"): ["kAByAm"], (5, "bahu"): ["kAByaH"],
        (6, "eka"): ["kasyAH"], (6, "dvi"): ["kayoH"], (6, "bahu"): ["kAsAm"],
        (7, "eka"): ["kasyAm"], (7, "dvi"): ["kayoH"], (7, "bahu"): ["kAsu"],
        (8, "eka"): ["kA"], (8, "dvi"): ["ke"], (8, "bahu"): ["kAH"],
    },
    ("kim", "napuMsaka"): {
        (1, "eka"): ["kim"], (1, "dvi"): ["ke"], (1, "bahu"): ["kAni"],
        (2, "eka"): ["kim"], (2, "dvi"): ["ke"], (2, "bahu"): ["kAni"],
        (3, "eka"): ["kena"], (3, "dvi"): ["kAByAm"], (3, "bahu"): ["kEH"],
        (4, "eka"): ["kasmE"], (4, "dvi"): ["kAByAm"], (4, "bahu"): ["keByaH"],
        (5, "eka"): ["kasmAt"], (5, "dvi"): ["kAByAm"], (5, "bahu"): ["keByaH"],
        (6, "eka"): ["kasya"], (6, "dvi"): ["kayoH"], (6, "bahu"): ["kezAm"],
        (7, "eka"): ["kasmin"], (7, "dvi"): ["kayoH"], (7, "bahu"): ["kezu"],
        (8, "eka"): ["kim"], (8, "dvi"): ["ke"], (8, "bahu"): ["kAni"],
    },
    ("idam", "strI"): {
        (1, "eka"): ["iyam"], (1, "dvi"): ["ime"], (1, "bahu"): ["imAH"],
        (2, "eka"): ["imAm"], (2, "dvi"): ["ime"], (2, "bahu"): ["imAH"],
        (3, "eka"): ["anayA"], (3, "dvi"): ["AByAm"], (3, "bahu"): ["ABiH"],
        (4, "eka"): ["asyE"], (4, "dvi"): ["AByAm"], (4, "bahu"): ["AByaH"],
        (5, "eka"): ["asyAH"], (5, "dvi"): ["AByAm"], (5, "bahu"): ["AByaH"],
        (6, "eka"): ["asyAH"], (6, "dvi"): ["anayoH"], (6, "bahu"): ["AsAm"],
        (7, "eka"): ["asyAm"], (7, "dvi"): ["anayoH"], (7, "bahu"): ["Asu"],
        (8, "eka"): ["iyam"], (8, "dvi"): ["ime"], (8, "bahu"): ["imAH"],
    },
    ("idam", "napuMsaka"): {
        (1, "eka"): ["idam"], (1, "dvi"): ["ime"], (1, "bahu"): ["imAni"],
        (2, "eka"): ["idam"], (2, "dvi"): ["ime"], (2, "bahu"): ["imAni"],
        (3, "eka"): ["anena"], (3, "dvi"): ["AByAm"], (3, "bahu"): ["eBiH"],
        (4, "eka"): ["asmE"], (4, "dvi"): ["AByAm"], (4, "bahu"): ["eByaH"],
        (5, "eka"): ["asmAt"], (5, "dvi"): ["AByAm"], (5, "bahu"): ["eByaH"],
        (6, "eka"): ["asya"], (6, "dvi"): ["anayoH"], (6, "bahu"): ["ezAm"],
        (7, "eka"): ["asmin"], (7, "dvi"): ["anayoH"], (7, "bahu"): ["ezu"],
        (8, "eka"): ["idam"], (8, "dvi"): ["ime"], (8, "bahu"): ["imAni"],
    },
    ("adas", "strI"): {
        (1, "eka"): ["asO"], (1, "dvi"): ["amU"], (1, "bahu"): ["amUH"],
        (2, "eka"): ["amUm"], (2, "dvi"): ["amU"], (2, "bahu"): ["amUH"],
        (3, "eka"): ["amuyA"], (3, "dvi"): ["amUByAm"], (3, "bahu"): ["amUBiH"],
        (4, "eka"): ["amuzyE"], (4, "dvi"): ["amUByAm"], (4, "bahu"): ["amUByaH"],
        (5, "eka"): ["amuzyAH"], (5, "dvi"): ["amUByAm"], (5, "bahu"): ["amUByaH"],
        (6, "eka"): ["amuzyAH"], (6, "dvi"): ["amuyoH"], (6, "bahu"): ["amUzAm"],
        (7, "eka"): ["amuzyAm"], (7, "dvi"): ["amuyoH"], (7, "bahu"): ["amUzu"],
        (8, "eka"): ["asO"], (8, "dvi"): ["amU"], (8, "bahu"): ["amUH"],
    },
    ("adas", "napuMsaka"): {
        (1, "eka"): ["adaH"], (1, "dvi"): ["amUnI"], (1, "bahu"): ["amUni"],
        (2, "eka"): ["adaH"], (2, "dvi"): ["amUnI"], (2, "bahu"): ["amUni"],
        (3, "eka"): ["amunA"], (3, "dvi"): ["amUByAm"], (3, "bahu"): ["amIBiH"],
        (4, "eka"): ["amuzmE"], (4, "dvi"): ["amUByAm"], (4, "bahu"): ["amIByaH"],
        (5, "eka"): ["amuzmAt"], (5, "dvi"): ["amUByAm"], (5, "bahu"): ["amIByaH"],
        (6, "eka"): ["amuzya"], (6, "dvi"): ["amuyoH"], (6, "bahu"): ["amIzAm"],
        (7, "eka"): ["amuzmin"], (7, "dvi"): ["amuyoH"], (7, "bahu"): ["amIzu"],
        (8, "eka"): ["adaH"], (8, "dvi"): ["amUnI"], (8, "bahu"): ["amUni"],
    },
    ("sarva", "napuMsaka"): {
        (1, "eka"): ["sarvam"], (1, "dvi"): ["sarve"], (1, "bahu"): ["sarvARi"],
        (2, "eka"): ["sarvam"], (2, "dvi"): ["sarve"], (2, "bahu"): ["sarvARi"],
        (3, "eka"): ["sarveRa"], (3, "dvi"): ["sarvAByAm"], (3, "bahu"): ["sarvEH"],
        (4, "eka"): ["sarvasmE"], (4, "dvi"): ["sarvAByAm"], (4, "bahu"): ["sarveByaH"],
        (5, "eka"): ["sarvasmAt"], (5, "dvi"): ["sarvAByAm"], (5, "bahu"): ["sarveByaH"],
        (6, "eka"): ["sarvasya"], (6, "dvi"): ["sarvayoH"], (6, "bahu"): ["sarvezAm"],
        (7, "eka"): ["sarvasmin"], (7, "dvi"): ["sarvayoH"], (7, "bahu"): ["sarvezu"],
        (8, "eka"): ["sarvam"], (8, "dvi"): ["sarve"], (8, "bahu"): ["sarvARi"],
    },
    ("gacCantI", "strI"): {
        (1, "eka"): ["gacCantIH"], (1, "dvi"): ["gacCantyO"], (1, "bahu"): ["gacCantyaH"],
        (2, "eka"): ["gacCantIm"], (2, "dvi"): ["gacCantyO"], (2, "bahu"): ["gacCantIH"],
        (3, "eka"): ["gacCantyA"], (3, "dvi"): ["gacCantIByAm"], (3, "bahu"): ["gacCantIBiH"],
        (4, "eka"): ["gacCantyE"], (4, "dvi"): ["gacCantIByAm"], (4, "bahu"): ["gacCantIByaH"],
        (5, "eka"): ["gacCantyAH"], (5, "dvi"): ["gacCantIByAm"], (5, "bahu"): ["gacCantIByaH"],
        (6, "eka"): ["gacCantyAH"], (6, "dvi"): ["gacCantyoH"], (6, "bahu"): ["gacCantInAm"],
        (7, "eka"): ["gacCantyAm"], (7, "dvi"): ["gacCantyoH"], (7, "bahu"): ["gacCantIzu"],
        (8, "eka"): ["gacCanti"], (8, "dvi"): ["gacCantyO"], (8, "bahu"): ["gacCantyaH"],
    },
    ("SreyasI", "strI"): {
        (1, "eka"): ["SreyasIH"], (1, "dvi"): ["SreyasyO"], (1, "bahu"): ["SreyasyaH"],
        (2, "eka"): ["SreyasIm"], (2, "dvi"): ["SreyasyO"], (2, "bahu"): ["SreyasIH"],
        (3, "eka"): ["SreyasyA"], (3, "dvi"): ["SreyasIByAm"], (3, "bahu"): ["SreyasIBiH"],
        (4, "eka"): ["SreyasyE"], (4, "dvi"): ["SreyasIByAm"], (4, "bahu"): ["SreyasIByaH"],
        (5, "eka"): ["SreyasyAH"], (5, "dvi"): ["SreyasIByAm"], (5, "bahu"): ["SreyasIByaH"],
        (6, "eka"): ["SreyasyAH"], (6, "dvi"): ["SreyasyoH"], (6, "bahu"): ["SreyasInAm"],
        (7, "eka"): ["SreyasyAm"], (7, "dvi"): ["SreyasyoH"], (7, "bahu"): ["SreyasIzu"],
        (8, "eka"): ["Sreyasi"], (8, "dvi"): ["SreyasyO"], (8, "bahu"): ["SreyasyaH"],
    },
    ("BavatI", "strI"): {
        (1, "eka"): ["BavatIH"], (1, "dvi"): ["BavatyO"], (1, "bahu"): ["BavatyaH"],
        (2, "eka"): ["BavatIm"], (2, "dvi"): ["BavatyO"], (2, "bahu"): ["BavatIH"],
        (3, "eka"): ["BavatyA"], (3, "dvi"): ["BavatIByAm"], (3, "bahu"): ["BavatIBiH"],
        (4, "eka"): ["BavatyE"], (4, "dvi"): ["BavatIByAm"], (4, "bahu"): ["BavatIByaH"],
        (5, "eka"): ["BavatyAH"], (5, "dvi"): ["BavatIByAm"], (5, "bahu"): ["BavatIByaH"],
        (6, "eka"): ["BavatyAH"], (6, "dvi"): ["BavatyoH"], (6, "bahu"): ["BavatInAm"],
        (7, "eka"): ["BavatyAm"], (7, "dvi"): ["BavatyoH"], (7, "bahu"): ["BavatIzu"],
        (8, "eka"): ["Bavati"], (8, "dvi"): ["BavatyO"], (8, "bahu"): ["BavatyaH"],
    },
}


class TestSubantaFullAudit(unittest.TestCase):
    def test_full_tables(self):
        e = SubantaEngine()
        total = 0
        misses = []
        for (stem, linga), golden in {**GOLDENS, **GOLDENS2, **GOLDENS3, **GOLDENS4, **GOLDENS5, **GOLDENS6}.items():
            got = e.decline(stem, linga)
            for key, exp_list in golden.items():
                total += 1
                got_list = got.get(key, [])
                if not exp_list:
                    if got_list:
                        misses.append(f"{stem}/{linga} {key}: want [] got {got_list}")
                    continue
                for exp in exp_list:
                    if exp not in got_list:
                        misses.append(f"{stem}/{linga} {key}: want {exp} got {got_list}")
        self.assertEqual(misses, [], f"{len(misses)}/{total} misses:\n" + "\n".join(misses[:20]))


if __name__ == "__main__":
    unittest.main()
